import type { Metadata } from 'next'
import { Container } from '@mui/material'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Header/>
          <Container>
            {children}
          </Container>
        </body>
    </html>
  )
}
